interface FinancialSummaryProps {
  estimatedLoss: number
  refundAmount: number
  operationalCost: number
  recoverableValue: number
}

function formatCurrency(value: number) {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(value)
}

function FinancialSummary({
  estimatedLoss,
  refundAmount,
  operationalCost,
  recoverableValue,
}: FinancialSummaryProps) {
  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
      <h2 className="text-lg font-semibold text-slate-900">
        Financial Summary
      </h2>

      <p className="mt-1 text-sm text-slate-500">
        Estimated monetary impact generated by ReturnIQ.
      </p>

      <div className="mt-6 space-y-5">
        <div className="flex items-center justify-between border-b border-slate-100 pb-3">
          <span className="text-sm text-slate-500">
            Refund Amount
          </span>

          <span className="font-semibold text-slate-900">
            {formatCurrency(refundAmount)}
          </span>
        </div>

        <div className="flex items-center justify-between border-b border-slate-100 pb-3">
          <span className="text-sm text-slate-500">
            Estimated Loss
          </span>

          <span className="font-semibold text-red-600">
            {formatCurrency(estimatedLoss)}
          </span>
        </div>

        <div className="flex items-center justify-between border-b border-slate-100 pb-3">
          <span className="text-sm text-slate-500">
            Operational Cost
          </span>

          <span className="font-semibold text-slate-900">
            {formatCurrency(operationalCost)}
          </span>
        </div>

        <div className="flex items-center justify-between">
          <span className="text-sm text-slate-500">
            Recoverable Value
          </span>

          <span className="font-semibold text-green-600">
            {formatCurrency(recoverableValue)}
          </span>
        </div>
      </div>
    </div>
  )
}

export default FinancialSummary