import {
  AlertTriangle, ArrowLeft, BadgeIndianRupee, CalendarDays, CheckCircle2, Clock3, CreditCard, MapPin, Package, ShieldAlert, Sparkles, Truck, UserRound,
} from "lucide-react"
import { useNavigate, useParams } from "react-router-dom"
import { useReturn } from "../hooks/useReturn"

function money(value: number) { return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value) }
function label(value?: string | null) { return value ? value.replaceAll("_", " ").replace(/\b\w/g, c => c.toUpperCase()) : "Not provided" }
function date(value?: string | null) { return value ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" }).format(new Date(value)) : "Not provided" }
function Detail({ title, value }: { title: string; value: React.ReactNode }) { return <div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{title}</p><p className="mt-1 break-words text-sm font-semibold text-slate-900 dark:text-slate-100">{value ?? "Not provided"}</p></div> }

function ReturnDetailsPage() {
  const navigate = useNavigate(); const { returnId } = useParams(); const { data: item, isLoading, isError, refetch } = useReturn(returnId)
  if (isLoading) return <div className="h-96 animate-pulse rounded-2xl bg-slate-200 dark:bg-slate-800"/>
  if (isError || !item) return <div className="rounded-2xl border border-red-200 bg-white p-10 text-center dark:border-red-900 dark:bg-slate-900"><AlertTriangle className="mx-auto h-12 w-12 text-red-500"/><h1 className="mt-4 text-xl font-semibold dark:text-white">Return details could not be loaded</h1><button onClick={() => refetch()} className="mt-5 rounded-xl bg-blue-600 px-4 py-2 text-white">Retry</button></div>
  const p = item.request_payload ?? {}
  return <div className="space-y-6">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><button onClick={() => navigate('/returns')} className="mb-3 inline-flex items-center gap-2 text-sm font-medium text-slate-500"><ArrowLeft className="h-4 w-4"/>Back to returns</button><h1 className="text-3xl font-bold text-slate-950 dark:text-white">Marketplace Return Details</h1><p className="mt-2 text-sm text-slate-500">Return {item.return_id}</p></div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-blue-50 px-3 py-1 text-sm font-semibold text-blue-700 dark:bg-blue-950/40 dark:text-blue-300">{label(item.status)}</span><span className="rounded-full bg-amber-50 px-3 py-1 text-sm font-semibold text-amber-700 dark:bg-amber-950/40 dark:text-amber-300">{label(item.risk_level)} risk</span></div></div>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      <article className="rounded-2xl border bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><ShieldAlert className="h-5 w-5 text-red-500"/><p className="mt-4 text-sm text-slate-500">Risk score</p><p className="mt-1 text-3xl font-bold dark:text-white">{item.risk_score}</p></article>
      <article className="rounded-2xl border bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><Sparkles className="h-5 w-5 text-blue-600"/><p className="mt-4 text-sm text-slate-500">Confidence</p><p className="mt-1 text-3xl font-bold dark:text-white">{Math.round(item.confidence*100)}%</p></article>
      <article className="rounded-2xl border bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><BadgeIndianRupee className="h-5 w-5 text-emerald-600"/><p className="mt-4 text-sm text-slate-500">Refund amount</p><p className="mt-1 text-2xl font-bold dark:text-white">{money(item.financial_impact.refund_amount)}</p></article>
      <article className="rounded-2xl border bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">{item.human_review_required ? <Clock3 className="h-5 w-5 text-amber-500"/> : <CheckCircle2 className="h-5 w-5 text-emerald-500"/>}<p className="mt-4 text-sm text-slate-500">Human review</p><p className="mt-1 text-xl font-bold dark:text-white">{item.human_review_required ? 'Required' : 'Not required'}</p></article>
    </section>
    <section className="grid gap-6 xl:grid-cols-2">
      <article className="rounded-2xl border bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-3"><Package className="h-5 w-5 text-blue-600"/><h2 className="text-lg font-bold dark:text-white">Order and product</h2></div><div className="mt-5 grid gap-5 sm:grid-cols-2"><Detail title="Amazon / marketplace order ID" value={p.marketplace_order_id || p.order_id}/><Detail title="External return ID" value={p.external_return_id}/><Detail title="Product" value={p.product_name}/><Detail title="Brand" value={p.brand}/><Detail title="Category" value={label(p.product_category)}/><Detail title="SKU" value={p.sku}/><Detail title="ASIN / Product ID" value={p.asin}/><Detail title="Serial number" value={p.serial_number}/><Detail title="Variant" value={p.variant}/><Detail title="Product price" value={money(p.product_price || 0)}/></div></article>
      <article className="rounded-2xl border bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-3"><UserRound className="h-5 w-5 text-blue-600"/><h2 className="text-lg font-bold dark:text-white">Customer</h2></div><div className="mt-5 grid gap-5 sm:grid-cols-2"><Detail title="Customer name" value={p.customer_name}/><Detail title="Customer ID" value={p.customer_id}/><Detail title="Email" value={p.customer_email}/><Detail title="Phone" value={p.customer_phone}/><Detail title="Shipping address" value={p.shipping_address}/><Detail title="Account age" value={`${p.customer_history?.account_age_days ?? 0} days`}/><Detail title="Total orders" value={p.customer_history?.total_orders}/><Detail title="Previous returns" value={p.customer_history?.total_returns}/></div></article>
      <article className="rounded-2xl border bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-3"><Truck className="h-5 w-5 text-blue-600"/><h2 className="text-lg font-bold dark:text-white">Shipment and payment</h2></div><div className="mt-5 grid gap-5 sm:grid-cols-2"><Detail title="Shipment ID" value={p.shipment_id}/><Detail title="Tracking ID" value={p.tracking_id}/><Detail title="Purchase date" value={date(p.purchase_date)}/><Detail title="Delivery date" value={date(p.delivery_date)}/><Detail title="Days after delivery" value={p.days_after_delivery}/><Detail title="Payment method" value={p.payment_method}/></div></article>
      <article className="rounded-2xl border bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-3"><CreditCard className="h-5 w-5 text-blue-600"/><h2 className="text-lg font-bold dark:text-white">Return and refund</h2></div><div className="mt-5 grid gap-5 sm:grid-cols-2"><Detail title="Return type" value={label(p.return_type)}/><Detail title="Return reason" value={p.return_reason}/><Detail title="Customer comment" value={p.customer_comment || p.return_reason}/><Detail title="Refund amount" value={money(item.financial_impact.refund_amount)}/><Detail title="Estimated loss" value={money(item.financial_impact.estimated_loss)}/><Detail title="Recoverable value" value={money(item.financial_impact.recoverable_value)}/></div></article>
    </section>
    <section className="grid gap-6 xl:grid-cols-[1.4fr_1fr]">
      <article className="rounded-2xl border bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="text-lg font-bold dark:text-white">AI assessment</h2><div className="mt-5 space-y-5"><Detail title="Recommendation" value={label(item.recommendation)}/><Detail title="Explanation" value={item.recommendation_reason}/><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Risk factors</p><div className="mt-3 space-y-3">{item.factors.map((f,i)=><div key={`${f.name}-${i}`} className="rounded-xl bg-slate-50 p-4 dark:bg-slate-950"><div className="flex justify-between gap-3"><p className="font-semibold dark:text-white">{label(f.name)}</p><span className="text-sm font-bold text-red-600">{f.impact>0?'+':''}{f.impact}</span></div><p className="mt-1 text-sm text-slate-500">{f.explanation}</p></div>)}</div></div></div></article>
      <article className="rounded-2xl border bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="text-lg font-bold dark:text-white">Decision timeline</h2><div className="mt-5 space-y-5"><div className="flex gap-3"><CalendarDays className="h-5 w-5 text-blue-600"/><div><p className="font-semibold dark:text-white">Return submitted</p><p className="text-sm text-slate-500">{date(item.created_at)}</p></div></div><div className="flex gap-3"><Sparkles className="h-5 w-5 text-emerald-600"/><div><p className="font-semibold dark:text-white">AI assessment completed</p><p className="text-sm text-slate-500">Recommendation: {label(item.recommendation)}</p></div></div><div className="flex gap-3"><Clock3 className="h-5 w-5 text-amber-500"/><div><p className="font-semibold dark:text-white">Current status</p><p className="text-sm text-slate-500">{label(item.status)}</p></div></div></div></article>
    </section>
  </div>
}
export default ReturnDetailsPage
